# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import AddNumbers_pb2 as AddNumbers__pb2


class AddNumbersStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.AddNumbers = channel.unary_unary(
        '/AddNumbers/AddNumbers',
        request_serializer=AddNumbers__pb2.input.SerializeToString,
        response_deserializer=AddNumbers__pb2.Number.FromString,
        )


class AddNumbersServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def AddNumbers(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_AddNumbersServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'AddNumbers': grpc.unary_unary_rpc_method_handler(
          servicer.AddNumbers,
          request_deserializer=AddNumbers__pb2.input.FromString,
          response_serializer=AddNumbers__pb2.Number.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'AddNumbers', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
