apiVersion: apps/v1
kind: Deployment
metadata:
  name: rest
spec:
  selector:
    matchLabels:
      app: rest
  replicas: 1
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
      - name: rest
        image: gcr.io/decoded-reducer-258105/rest
        ports:
        - containerPort: 5000 
          protocol: TCP
