#!/bin/sh

#
# Try to find the streaming JAR
#

PLACES="/usr/lib/hadoop-mapreduce/hadoop-streaming.jar /usr/local/hadoop/share/hadoop/tools/lib/hadoop-streaming-2.9.2.jar /home/tar/Downloads/jar_files/hadoop-streaming-2.9.2.jar"
STREAM=""

for place in $PLACES; do
    if [ -f $place ]
    then
	STREAM="$place"
    fi
done

if [ -z "$STREAM" ]
then
    echo "Unable to find your streaming JAR"
    exit 1
fi

hdfs dfs -mkdir /user
hdfs dfs -mkdir /user/csci2400.anonymous
   
hdfs dfs -rm -r stream-output1
hdfs dfs -rm -r stream-output2
hdfs dfs -rm -r output

hadoop jar $STREAM \
	-mapper CheckCitationCountMapper.py \
	-reducer CheckCitationCountReducer.py \
	-file CheckCitationCountMapper.py -file CheckCitationCountReducer.py \
	-input input -output stream-output1

hdfs dfs -cp apat63_99.txt /user/csci2400.anonymous/stream-output1

hadoop jar $STREAM \
	-mapper CheckCitationCountMapper2.py \
	-reducer CheckCitationCountReducer2.py \
	-file CheckCitationCountMapper2.py -file CheckCitationCountReducer2.py \
	-input stream-output1 -output stream-output2

hdfs dfs -cp apat63_99.txt /user/csci2400.anonymous/stream-output2

hadoop jar $STREAM \
	-mapper CheckCitationCountMapper3.py \
	-reducer CheckCitationCountReducer3.py \
	-file CheckCitationCountMapper3.py -file CheckCitationCountReducer3.py \
	-input stream-output2 -output output

	
